# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZJQgVpUewOuIeifcmONzEt8dvG1R_tRx
"""

# -*- coding: utf-8 -*-
"""Assignment 8-1
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1qrWpd9Gh3WxYkqXcjhcqyfxkXMjScNtn
"""
 
# -*- coding: utf-8 -*-
"""Assignment8.ipynb
 
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1K4uGtnhOtv4P44277zg-xnL6sPEPhIgA
"""
#Code by Rapolu Ooha
# July 2,2021
 
import numpy as np
import matplotlib.pyplot as plt
 
#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
 
#Generating and plotting line
A=np.array([0,0])
B=np.array([0,9])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:])
 
 
#Generating and plotting line x+y=9
C=np.array([0,9])
D=np.array([9,0])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='x+y=9')
 
 
#Generating and plotting line
E=np.array([0,0])
F=np.array([9,0])
EF=line_gen(E,F) 
plt.plot(EF[0,:],EF[1,:])
 

#Generating and plotting line x=y
G=np.array([0,0])
H=np.array([2,2])
GH=line_gen(G,H)
plt.plot(GH[0,:],GH[1,:],label='x=y')
 
 
#Shading Required Region
x1=[9,0.05,0]
y1=[0.05,9,0]
plt.fill(x1,y1,color='green',alpha=0.3)
 
#Labelling points
plt.plot(9,0,'o',color='r')
plt.text(9,0,'A(9,0)')
plt.plot(0,0,'o',color='r')
plt.text(0,0,'O(0,0)')
plt.plot(0,9, 'o', color='r')
plt.text(0,9,'B(0,9)')
plt.plot(2, 2,'o',color='r')
plt.text(2,2,'C(2,2)')
 
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid()
plt.axis('equal')